### PR TITLE
comrades.csv update

### PR DESCRIPTION
**Pull request by torkus**
consolidating and cleaning up the list of comrades

* title case column names
* title case programming language
* removed question marks
* merged `comrades.csv` and `fallen-comrades.csv`, unmaintained managers at the top
* re-introduced `maintained` column
* github projects are now consistently `$owner/$project-name`, except in cases where owner and project name are the same (WorldOfAddons, OpenAddOnManager)
* supported platform caveat ('*') is ruffling feathers. make the wording and conditions for that caveat asterisk clear and unambiguous
* add self (wowman) to list
* add wowmatrix back to list? I think so, lets not play favourites no matter how disreputable
* add twitch client to list? I think so, there is no 'official' addon manager for us to be 'alternative' to

fyi @layday

### CODE REVIEW

**Comment by torkus** [comment]
this is in anticipation of a [side project](https://github.com/ogri-la/wowman-comrades) I'm playing with:

Screenshot at 2019-09-28 22-12-45

**Comment by layday** [comment]
lcurse is FOSS.

**Comment by torkus** [comment]
> lcurse is FOSS.

no, I don't think it is: https://en.wikipedia.org/wiki/Unlicense

FSF say public domain works are compatible with the GPL, but a Free/libre licence is different from compatibility for inclusion in a GPL'd work.

The OSI have [clear definitions](https://opensource.org/osd) of what constitutes open source software and they all revolve around copyright ownership, which the Unlicence claims to not participate in. You can find a list of approved licences here: https://opensource.org/licenses/alphabetical

I appreciate the intent of the Unlicence but it seems to have [real (interesting) problems](https://web.archive.org/web/20170301020915/https://lists.opensource.org/pipermail/license-review/2012-January/001386.html).

**Comment by torkus** [comment]
(which is why there is a 'source available' column ;)

**Comment by layday** [comment]
The FSF are of the [opinion](https://www.gnu.org/licenses/license-list.en.html#Unlicense) that the Unlicense comes with a lax licence to fall back on where public domain dedication is not practicable, so whatever the Unlicense authors might claim is (might be) contradicted by the licence itself - which, I suppose, is not a great place to find oneself in.  But yeah, if it's not OSI-approved, then I guess...

**Comment by layday** [comment]
Really nice work with the site. I was going to suggest 'yes*' should show yeses without asterisks as well but I see you've already done that :)

**Comment by torkus** [comment]
yes ;)

I have a [TODO](https://github.com/ogri-la/wowman-comrades/blob/master/TODO.md) list for that mini-site as well that I'll work through when I want a break from wowman. 

It's been a fun little weekend project.

**Pull request merged**
